// Generated by LispyScript v0.3.1
var _LS = (_LS || {});
_LS.expandTag = function(name,attr) {
    var args = Array.prototype.slice.call(arguments);
    var ret = "";
    return ((Object.prototype.toString.call(name) === "[object String]") ?
        (function() {
            ret = ("<" + name);
            args.shift();
            ((Object.prototype.toString.call(attr) === "[object Object]") ?
                (function() {
                    ret = (ret + (function() {
                        var ___ret = "";
                        (function(o,f,s) {
                            var _k = Object.keys(o);
                            return (_k).forEach(function(elem) {
                                return f.call(s,o[elem],elem,o);
                            });
                        })(attr,function(value,key) {
                            ___ret = (___ret + [" ",key,"=","\"",value,"\""].join(''));
                        });
                        return ___ret;
                    })());
                    return args.shift();
                })() :
                undefined);
            (((args.length > 0) || (name === "script")) ?
                ret = [ret,">",args.join(""),"</",name,">"].join('') :
                ret = (ret + "/>"));
            return ret;
        })() :
        "");
};
var index = ("<!DOCTYPE html>\n" + _LS.expandTag("html",{lang:"en"},_LS.expandTag("head",_LS.expandTag("title","richever tech"),_LS.expandTag("script",{type:"text/javascript", src:"code/main.js"})),_LS.expandTag("body",_LS.expandTag("div","welcome"))));
var express = require('express');
var app = express();
app.use(express.static((__dirname + '/client')));
app.get('/',function(req,res) {
    return res.send(index);
});
app.listen(3000);
console.log('Listening on port 3000');
